services:
    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        image: laravel-boilerplate-nginx:latest
        ports:
            - '${APP_PORT:-80}:80'
            - '${APP_HTTPS_PORT:-443}:443'
        environment:
            APP_DOMAIN: '${APP_DOMAIN:-laravel.test}'
        volumes:
            - ./:/var/www/html:delegated
            - sail-ssl-certs:/etc/nginx/certs
            - sail-mkcert-ca:/root/.local/share/mkcert
        networks:
            - sail
        depends_on:
            - laravel.test
    laravel.test:
        build:
            context: ./docker/8.4
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.4/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            APP_URL: 'https://${APP_DOMAIN:-laravel.test}'
        volumes:
            - ./:/var/www/html:delegated
            - /var/www/html/node_modules  # Keep container's node_modules isolated
            - ~/.composer/cache:/home/sail/.composer/cache:delegated
        networks:
            - sail
        depends_on:
            - pgsql
            - valkey
            - mailpit
    pgsql:
        image: 'postgres:17'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sail-pgsql-laravel-boilerplate:/var/lib/postgresql/data'
            - './docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s
    valkey:
        image: 'valkey/valkey:alpine'
        ports:
            - '${FORWARD_VALKEY_PORT:-6379}:6379'
        volumes:
            - 'sail-valkey:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - valkey-cli
                - ping
            retries: 3
            timeout: 5s
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-pgsql-laravel-boilerplate:
        driver: local
    sail-valkey:
        driver: local
    sail-ssl-certs:
        driver: local
    sail-mkcert-ca:
        driver: local
