name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 3
      matrix:
        php: [ 8.4 ]

    services:

      redis:
        image: redis:7.4
        ports:
          - 6379:6379

    name: Test with PHP ${{ matrix.php }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Setup PHP Environment
        uses: ./.github/actions/setup
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Install Project Dependencies
        run: composer install -q --no-interaction --no-progress

      - name: Install Node.js Dependencies
        run: npm install

      - name: Build Assets
        run: npm run build

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: migrate and seed
        run: php artisan migrate --seed

      - name: module seed
        run: php artisan module:seed --all

      - name: Run Tests
        run: composer test
